/**
 * AUTO-GENERATED by scripts/port-resw.ts — DO NOT EDIT BY HAND.
 *
 * Static map of every ported UWP locale to its flattened string table. Imported
 * statically so the bundler can resolve + tree-shake; no runtime fs (PA-8 clean).
 * Regenerate with: tsx scripts/port-resw.ts   (verify with --check).
 */

import l0 from './ar-YE';
import l1 from './bg-BG';
import l2 from './cs-CZ';
import l3 from './de-CH';
import l4 from './de-DE';
import l5 from './en-US';
import l6 from './es-ES';
import l7 from './fi-FI';
import l8 from './fr-FR';
import l9 from './hi-IN';
import l10 from './hr-HR';
import l11 from './hu-HU';
import l12 from './it-IT';
import l13 from './ja-JP';
import l14 from './ka-GE';
import l15 from './ko-KR';
import l16 from './nl-NL';
import l17 from './or-IN';
import l18 from './pl-PL';
import l19 from './pt-BR';
import l20 from './pt-PT';
import l21 from './ru-RU';
import l22 from './sr-cyrl';
import l23 from './sr-Latn';
import l24 from './tr-TR';
import l25 from './uk-UA';
import l26 from './vi-VN';
import l27 from './zh-CN';
import l28 from './zh-TW';

export type { LocaleTable } from './types';

/** Every locale tag ported from the UWP Strings/ dir (BCP-47, source casing). */
export const SUPPORTED_LOCALES = [
  'ar-YE',
  'bg-BG',
  'cs-CZ',
  'de-CH',
  'de-DE',
  'en-US',
  'es-ES',
  'fi-FI',
  'fr-FR',
  'hi-IN',
  'hr-HR',
  'hu-HU',
  'it-IT',
  'ja-JP',
  'ka-GE',
  'ko-KR',
  'nl-NL',
  'or-IN',
  'pl-PL',
  'pt-BR',
  'pt-PT',
  'ru-RU',
  'sr-cyrl',
  'sr-Latn',
  'tr-TR',
  'uk-UA',
  'vi-VN',
  'zh-CN',
  'zh-TW',
] as const;

export type SupportedLocale = (typeof SUPPORTED_LOCALES)[number];

/** locale tag -> flattened { key: value } table. */
export const LOCALE_TABLES: Record<SupportedLocale, import('./types').LocaleTable> = {
  'ar-YE': l0,
  'bg-BG': l1,
  'cs-CZ': l2,
  'de-CH': l3,
  'de-DE': l4,
  'en-US': l5,
  'es-ES': l6,
  'fi-FI': l7,
  'fr-FR': l8,
  'hi-IN': l9,
  'hr-HR': l10,
  'hu-HU': l11,
  'it-IT': l12,
  'ja-JP': l13,
  'ka-GE': l14,
  'ko-KR': l15,
  'nl-NL': l16,
  'or-IN': l17,
  'pl-PL': l18,
  'pt-BR': l19,
  'pt-PT': l20,
  'ru-RU': l21,
  'sr-cyrl': l22,
  'sr-Latn': l23,
  'tr-TR': l24,
  'uk-UA': l25,
  'vi-VN': l26,
  'zh-CN': l27,
  'zh-TW': l28,
};

/** The base locale every other table falls back to for missing keys. */
export const BASE_LOCALE: SupportedLocale = 'en-US';
